# Generated by Django 6.0.3 on 2026-03-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('barcode_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
