# Generated by Django 6.0.3 on 2026-03-17 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='barcode_image',
            field=models.ImageField(blank=True, upload_to='barcodes/'),
        ),
        migrations.AddField(
            model_name='student',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes/'),
        ),
    ]
