# Generated by Django 5.2.12 on 2026-03-23 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='scanned_id',
            field=models.CharField(blank=True, help_text='Temporary field to store scanned student ID.', max_length=100, null=True),
        ),
    ]
