# Generated by Django 6.0.3 on 2026-03-17 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_first_name_student_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
    ]
